### PR TITLE
fix(version): update get last commit hash info regex to support all timezone

### LINKED ISSUE #867: Variable $since of type GitTimestamp! was provided invalid value
### Describe the bug

Hi
thank's for developing this project, and also good issue template!

When I want to release the new version with lerna lite have error, no solution found when googling
I'm try update my github token, release manually and then retry 

I have manually captured several tags and releases
Can it cause problems at work?

### Expectation

release next version

### Reproduction

```sh
yarn lerna version --force-publish
```

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "https://raw.githubusercontent.com/lerna-lite/lerna-lite/main/packages/cli/schemas/lerna-schema.json",
  "version": "4.20.0",
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "loglevel": "verbose",
  "command": {
    "version": {
      "conventionalCommits": true,
      "changelog": true,
      "changelogPreset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "feature",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          },
          {
            "type": "perf",
            "section": "Performance Improvements"
          },
          {
            "type": "revert",
            "section": "Reverts"
          },
          {
            "type": "refactor",
            "section": "Code Refactoring"
          },
          {
            "type": "chore",
            "section": "Miscellaneous Chores"
          },
          {
            "type": "docs",
            "section": "Documentation",
            "hidden": true
          },
          {
            "type": "doc",
            "section": "Documentation",
            "hidden": true
          },
          {
            "type": "deps",
            "section": "Dependencies update",
            "hidden": true
          },
          {
            "type": "style",
            "section": "Styles",
            "hidden": true
          },
          {
            "type": "test",
            "section": "Tests",
            "hidden": true
          },
          {
            "type": "build",
            "section": "Build System",
            "hidden": true
          },
          {
            "type": "ci",
            "section": "Continuous Integration",
            "hidden": true
          }
        ]
      },
      "changelogIncludeCommitsClientLogin": " by @%l",
      "ignoreChanges": [
        "*.md"
      ],
      "message": "release:",
      "private": true,
      "forceGitTag": true,
      "signGitTag": true,
      "signGitCommit": true,
      "push": true,
      "createRelease": "github"
    },
    "run": {
      "stream": true
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv [object Object]
1 notice cli v3.4.0
2 verbose rootPath /Users/njfamirm/repo/alwatr/soffit-order
3 silly createGitHubClient
4 verbose project packages packages/*
5 info current project version 4.20.0
6 silly isAnythingCommitted
7 verbose isAnythingCommitted 1
8 silly currentBranch
9 verbose currentBranch next
10 silly remoteBranchExists
11 silly isBehindUpstream
12 silly isBehindUpstream next is behind origin/next by 0 commit(s) and ahead by 0
13 silly git-describe parsed => {"lastTagName":"v4.16.5","lastVersion":"v4.16.5","refCount":"30","sha":"120197c","isDirty":false}
14 silly git getCurrentBranchOldestCommitSinceLastTag
15 verbose exec git log v4.16.5..HEAD --format="%h %aI" --reverse
16 info oldestCommitSinceLastTag commit found since last tag: v4.16.5 - (SHA) undefined - undefined
17 silly parseGitRepo
18 verbose git config --get remote.origin.url
19 silly createGitHubClient
20 error GraphqlResponseError: Request failed due to following response errors:
20 error  - Variable $since of type GitTimestamp! was provided invalid value
20 error     at /Users/njfamirm/.yarn/berry/cache/@octokit-graphql-npm-7.1.0-9956e50359-10c0.zip/node_modules/@octokit/graphql/dist-node/index.js:113:13
20 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
20 error     at async getGithubCommits (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
```
</p></details>

<details><p>

<summary>console log</summary>
```txt
lerna-lite notice cli v3.4.0
lerna-lite verb rootPath /Users/njfamirm/repo/alwatr/soffit-order
lerna-lite verb project packages packages/*
lerna-lite info current project version 4.20.0
lerna-lite verb isAnythingCommitted 1
lerna-lite verb currentBranch next
lerna-lite verb exec git log v4.16.5..HEAD --format="%h %aI" --reverse
lerna-lite info oldestCommitSinceLastTag commit found since last tag: v4.16.5 - (SHA) undefined - undefined
lerna-lite verb git config --get remote.origin.url
lerna-lite ERR! GraphqlResponseError: Request failed due to following response errors:
lerna-lite ERR!  - Variable $since of type GitTimestamp! was provided invalid value
lerna-lite ERR!     at /Users/njfamirm/.yarn/berry/cache/@octokit-graphql-npm-7.1.0-9956e50359-10c0.zip/node_modules/@octokit/graphql/dist-node/index.js:113:13
lerna-lite ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna-lite ERR!     at async getGithubCommits (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

GraphqlResponseError: Request failed due to following response errors:
 - Variable $since of type GitTimestamp! was provided invalid value
    at /Users/njfamirm/.yarn/berry/cache/@octokit-graphql-npm-7.1.0-9956e50359-10c0.zip/node_modules/@octokit/graphql/dist-node/index.js:113:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGithubCommits (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
    at async VersionCommand.initialize (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/version-command.js:164:44) {
  request: {
    query: 'query getCommits($repo: String!, $owner: String!, $branchName: String!, $pageSize: Int!, $since: GitTimestamp!) {\n' +
      '    repository(name: $repo, owner: $owner) {\n' +
      '      ref(qualifiedName: $branchName) {\n' +
      '        target { ... on Commit {\n' +
      '            history(first: $pageSize, since: $since ) {\n' +
      '              nodes { oid, message, author { name, user { login }}}\n' +
      '              pageInfo { hasNextPage, endCursor }\n' +
      '  }}}}}}',
    variables: {
      owner: 'njfamirm',
      repo: 'soffit-order',
      afterCursor: '',
      branchName: 'next',
      pageSize: 100,
      since: undefined
    }
  },
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 27 May 2024 05:57:31 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '6EF1:4CCC8:31CB1D4:518BE97:665420CA',
    'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, admin:ssh_signing_key, audit_log, codespace, copilot, delete:packages, delete_repo, gist, notifications, project, repo, user, workflow, write:discussion, write:packages',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4992',
    'x-ratelimit-reset': '1716792984',
    'x-ratelimit-resource': 'graphql',
    'x-ratelimit-used': '8',
    'x-xss-protection': '0'
  },
  response: {
    errors: [
      {
        extensions: { value: null, problems: [ [Object] ] },
        locations: [ { line: 1, column: 90 } ],
        message: 'Variable $since of type GitTimestamp! was provided invalid value'
      }
    ]
  },
  errors: [
    {
      extensions: {
        value: null,
        problems: [ { path: [], explanation: 'Expected value to not be null' } ]
      },
      locations: [ { line: 1, column: 90 } ],
      message: 'Variable $since of type GitTimestamp! was provided invalid value'
    }
  ],
  data: undefined
}
```
</p></details>

### Environment Info

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 152.44 MB / 8.00 GB
    Shell: 5.2.26 - /opt/homebrew/bin/bash
  Binaries:
    Node: 22.2.0 - /private/var/folders/nk/6cds2s5gn2n395jpk00gn/T/xfs-b7eccce5/node
    Yarn: 4.2.2 - /private/var/folders/nk/6cds12s5gnn395jwk000gn/T/xfs-b7eccce5/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 17.4.1

### Used Package Manager

yarn >= 2.x

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by njfamirm**
## Motivation and Context

fixes #867 

## Types of changes

- [ ] Chore (change that has absolutely no effect on users)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by njfamirm** [comment]
Unfortunately, I don't have enough mastery and time to write the desired test

Thank you for developing this project!

**Comment by ghiscoding** [comment]
Thanks I'll add unit tests in a separate PR

**Comment by ghiscoding** [comment]
@njfamirm thanks for the contribution, it's released under v3.5.2.

**Comment by AliMD** [comment]
> v3.5.2

Is it released? Im still have same issue of #867 in version 3.7.0.

**Comment by ghiscoding** [comment]
yes

**Pull request merged**
