### PR TITLE
feat(version): add `--push-tags-one-by-one`, fixes #701

### LINKED ISSUE #701: Allow to push tags one by one to overcome GitHub limit
### Clear and concise description of the problem

Hi, I run into a weird limitation. Github workflows aren't triggered when more than 3 tags are pushed simultaneously. This becomes relevant in `independent` mode. See here for more context https://github.com/lerna/lerna/issues/2218. I first wanted to use `--no-follow-tags` but it doesn't exist in lerna-lite. `--no-push` also has no impact on pushing tags. https://github.com/lerna-lite/lerna-lite/blob/3e7dcb7fcc9bb5d56b57141f23572a67b8e3b073/packages/version/src/version-command.ts#L840

I tested https://github.com/lerna/lerna/issues/2218#issuecomment-1662185323 which unfortunately doesn't work :disappointed:

### Suggested solution

Introduce a new field `--push-tags-serial` to prevent pushing all tags simultaneously.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by ghiscoding**
## Description

Push Git tags one by one

## Motivation and Context

- possibly fixes #701 
- when running Lerna version in `independent` mode, user could overcome GitHub limit

## Types of changes

- [ ] Chore (change that has absolutely no effect on users)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@StarpTech I'm not at all sure if that would fix the issue you brought in issue #701, so I'd like to have your opinion. I tried in dry-run mode by switching Lerna-Lite from fixed version to independent mode. I also did not try the Git commands either, so I have no idea if it would work or fail.

So do you think that would work or is it going in the wrong direction? Because if that doesn't work then I have no idea on how else to address the problem. 

Here's 1 Git command
```sh
git push --no-verify --atomic origin @lerna-lite/cli@4.0.0 main
```

image

**Comment by ghiscoding** [comment]
no feedback provided, but let's go ahead with it in a new release. @StarpTech if you have a chance to try it in the future and confirm that it works, that would be great. I think the PR will fix the GitHub limit. Cheers

**Comment by StarpTech** [comment]
Hi, in your repo, were you able to reproduce the issue?

**Comment by ghiscoding** [comment]
@StarpTech no since the simple repo I created to test this only has 2 packages so I won't hit the limit, however I tested the git push 1 by 1 and it seems to be working as expected.

**Pull request merged**
