### PR TITLE
fix(config): catch initialization errors, update cosmiconfig

### PR DESCRIPTION
**Pull request by d-fischer**
## Description

Fix initialization of cosmiconfig to catch possible JSON errors.

## Motivation and Context

Make sure cosmiconfig can be up to date.

## How Has This Been Tested?

I ran `pnpm jest packages/core/src/project/__tests__/project.spec.ts` and it's all green.

## Types of changes

- [ ] Chore (change that has absolutely no effect on users)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed. (I did not run the full suite, only the project tests, as the full suite takes way too long on my machine apparently [hope CI does better])

### CODE REVIEW

**Comment by d-fischer** [comment]
I don't see how this could possibly decrease coverage 🤔

**Comment by ghiscoding** [comment]
@d-fischer hey thanks a lot for the PR, this is very appreciate, I went and opened the codecov result and the decrease is from `project.ts` file on the line shown below, so the default throw is no longer being called by the tests.. but personally I don't care much about the coverage, what I care is that it doesn't break. Should I merge as it is? It looks fine by me. Thanks a lot

image

**Comment by d-fischer** [comment]
It's now all green, no more coverage worries.

**Comment by ghiscoding** [comment]
yeah thanks a ton for the PR, have a great weekend 😄

**Pull request merged**
